---
- name: Create Proxmox API user
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    proxmox_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
  tasks:
    - name: Create user
      uri:
        url: "https://{{ proxmox_host }}:8006/api2/json/access/users"
        method: POST
        user: "root@pam"
        password: "{{ vault_proxmox_root_pw }}"
        force_basic_auth: true
        validate_certs: false
        body_format: form-urlencoded
        body:
          userid: "{{ api_username }}@pve"
          password: "{{ vault_automation_user_pw }}"
          comment: "Automation user"
      register: user_result
      failed_when: user_result.status not in [200, 400]

    - name: Create token
      uri:
        url: "https://{{ proxmox_host }}:8006/api2/json/access/users/{{ api_username }}@pve/token/packer"
        method: POST
        user: "root@pam"
        password: "{{ vault_proxmox_root_pw }}"
        force_basic_auth: true
        validate_certs: false
        body_format: form-urlencoded
        body:
          comment: "Packer token"
      register: token_result
      failed_when: token_result.status not in [200, 400]

    - name: Show token
      debug:
        msg: "{{ api_username }}@pve!packer={{ token_result.json.data.value }}"
