- hosts: localhost
  connection: local
  vars:
    image_path: "{{ lookup('env','GITHUB_WORKSPACE') }}/packer/output/ubuntu-{{ ubuntu_version }}.qcow2"
    template_name: "ubuntu-{{ ubuntu_version }}-template"
  tasks:
    - name: Import image to Proxmox as a VM
      community.general.proxmox:
        api_user: "{{ lookup('env','PPROXMOX_USER') }}"
        api_password: "{{ lookup('env','PPROXMOX_PASSWORD') }}"
        api_host: "{{ lookup('env','PPROXMOX_HOST') }}"
        node: "{{ lookup('env','PPROXMOX_NODE') | default('pve') }}"
        vmid: 9001
        name: "{{ template_name }}"
        storage: "{{ lookup('env','PPROXMOX_STORAGE') | default('local-lvm') }}"
        iso: ""
        clone: no
        force: yes
        state: present
        scsi0: "{{ image_path }},backup=0"
        ostype: l26
        hotplug: 1
        accept_eula: yes
      delegate_to: localhost

    - name: Convert VM to template
      community.general.proxmox:
        api_user: "{{ lookup('env','PPROXMOX_USER') }}"
        api_password: "{{ lookup('env','PPROXMOX_PASSWORD') }}"
        api_host: "{{ lookup('env','PPROXMOX_HOST') }}"
        node: "{{ lookup('env','PPROXMOX_NODE') | default('pve') }}"
        vmid: 9001
        template: true
        state: present
      delegate_to: localhost
