# Generato automaticamente da Terraform — non modificare manualmente.
# Copiare in: kubespray/inventory/homelab/hosts.ini

[kube_control_plane]
k8s-master-1 ansible_host=192.168.0.150 ansible_user=ubuntu
k8s-master-2 ansible_host=192.168.0.151 ansible_user=ubuntu
k8s-master-3 ansible_host=192.168.0.152 ansible_user=ubuntu

[kube_node]
k8s-worker-1 ansible_host=192.168.0.155 ansible_user=ubuntu
k8s-worker-2 ansible_host=192.168.0.156 ansible_user=ubuntu
k8s-worker-3 ansible_host=192.168.0.157 ansible_user=ubuntu

[etcd:children]
kube_control_plane

[k8s_cluster:children]
kube_control_plane
kube_node

[calico_rr]
